name: xeus-zmq
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  - pkg-config
  - ninja
  # Host dependencies
  - zeromq
  - zeromq-static
  - cppzmq
  - xeus>=5.0.0,<6.0
  - OpenSSL 
  - libopenssl-static
  - nlohmann_json=3.11.3
  # Test dependencies
  - doctest >= 2.4.6
  - pytest
  - jupyter_kernel_test>=0.6,<0.7
