name: xeus-zmq
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  - pkg-config
  - ninja
  # Host dependencies
  - zeromq
  - zeromq-static
  - cppzmq
  - xtl=0.7
  - xeus>=4.0.3,<5.0
  - OpenSSL=1
  - libopenssl-static=1
  - nlohmann_json=3.11.3
  - libuvw
  # Test dependencies
  - doctest >= 2.4.6
  - pytest
  - jupyter_kernel_test>=0.6,<0.7
